firstwebsite/firstwebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

firstwebsite/music/urls.py
from django.conf.urls import url
from music import views

app_name = 'music'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    #/music/(album id)/
    url(r'^(?P<album_id>[0-9]+)/$',views.detail, name='detail'),
    #/music/(album id)/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite, name='favorite'),

]

firstwebsite/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

firstwebsite/music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from .models import Album, Song
from django.shortcuts import render, get_object_or_404

def index(request):
    all_albums = Album.objects.all()
    context = {
        'all_albums': all_albums
    }
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html',{
        'album': album,
        'error_message': "ERROR"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

firstwebsite/music/templates/music/detail.html
<img src = "{{album.album_logo}}">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>

{% if error_message %}
  <p><strong>{{error_message}}</strong></p>
{% endif %}


<form class="" action="{% url 'music:favorite' album.id%}" method="post">
  {% csrf_token %}
  {% for song in album.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{song.id}}">
    <label for="song{{ forloop.counter }}">
      {{ song.song_title }}
      {% if song.is_favorite%}
      <h2> text </h2>
      {% endif %}
    </label><br>
  {% endfor %}
  <input type="submit" value="favorite">
</form>

firstwebsite/music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />

<nav class="navbar navbar-default">
  <div class="container-fluid">
      <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'music:index' %}">Music</a>
      </div>
  </div>
</nav>

{% if all_albums %}
<ul>
  {% for album in all_albums %}
  <li><a href="{% url 'music:detail' album.id%}"> {{album.album_title}} </a></li>
  {% endfor%}
</ul>
{% else %}
  <h3> You don't have any albums</h3>
{% endif %}